[tool.isort]
line_length = 100
multi_line_output = 3
known_first_party = "sigstore"
include_trailing_comma = true

[tool.black]
line-length = 100

[tool.coverage.run]
# don't attempt code coverage for the CLI entrypoints
omit = ["sigstore/_cli.py"]
